import { type Metadata } from "next";
import { Geist } from "next/font/google";
import "~/styles/globals.css";

import { SessionProvider } from "next-auth/react";
import Navbar from "~/components/shared/Navbar";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`font-sans`}>
      <body>
        <SessionProvider>
          <TRPCReactProvider>
            <Navbar />
            <main className="container mx-auto max-w-4xl py-8">

            {children}
            </main>
          </TRPCReactProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
